> Se debe recordar que para sumar matrices, estas deben tener las mismas dimesiones. Sin embargo, se puede sumar una matriz con un vector, en este caso; para poderlo hacer el vector debe tener el mismo número de columnas que la matriz. El vector se repetirá tantas veces como filas tenga la matriz. Esto último se conoce como *broadcasting*, completar el elemento de menor dimesión hasta completar o igualar al de mayor dimensión.

A continuación un ejemplo de lo anterior.

In [1]:
import numpy as np

In [2]:
matriz = np.array([[5,10,15,20,25],[2,4,6,8,10],[6,12,18,24,36],[7,14,21,28,35],[9,18,27,36,45]])
vector = np.array([10,20,30,40,50])
resultado = matriz + vector
print(resultado)

[[15 30 45 60 75]
 [12 24 36 48 60]
 [16 32 48 64 86]
 [17 34 51 68 85]
 [19 38 57 76 95]]
