In [36]:
import numpy as np

matriz = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matriz.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [37]:
matriz = np.array([[1,0,0,0,0],
                [0,2,0,0,0],
                [0,0,3,0,0],
                [0,0,0,4,0],
                [0,0,0,0,5]])

print(np.linalg.det(matriz))

119.99999999999997


In [38]:
vector = np.array([-50,-25,0,25,100,-300])
print(np.linalg.norm(vector,ord=0))


5.0


In [39]:
v1 = np.array([0,1])
v2 = np.array([1,0])

print(v1.T.dot(v2))

norma_1 = np.linalg.norm(v1)
norma_2 = np.linalg.norm(v2)

print(norma_1 * norma_2 * np.cos(np.deg2rad(45)))

0
0.7071067811865476


In [40]:
vector =np.array([0.5,0.5,0.5,0.5])
print(np.linalg.norm(vector,ord=2))

1.0


In [43]:
v=np.array([7,-7,3])
u=np.array([1,1,0])
w=np.array[[0,0,1]]

print(np.dot(v,u))

TypeError: 'builtin_function_or_method' object is not subscriptable