In [4]:
import numpy as np

vector = np.array([1,2,3,4,5])
A = np.diag(vector)
print(A) # np.diag crea la matriz diagonal del vector

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


El cálculo de una matriz diagonal, es relativamente fácil. Simplemente se divide cada uno de los elementos de la diagonal por el mismo. Un ejemplo.

$A=\begin{bmatrix}1&0&0&0&0\\0&2&0&0&0\\0&0&3&0&0\\0&0&0&4&0\\0&0&0&0&5\end{bmatrix} \to
A^{-1}=\begin{bmatrix}1&0&0&0&0\\0&\frac{1}{2}&0&0&0\\0&0&\frac{1}{3}&0&0\\0&0&0&\frac{1}{4}&0\\
0&0&0&0&\frac{1}{5}\end{bmatrix}$

Comprobemoslo ahora con python

In [11]:
A_inv = np.linalg.inv(A) # Calculamos la inversa de A
print('-'*20,'Inversa de A:')
print(A_inv)
print('-'*20,'A·A¯¹')
print(A.dot(A_inv))

-------------------- Inversa de A:
[[1.         0.         0.         0.         0.        ]
 [0.         0.5        0.         0.         0.        ]
 [0.         0.         0.33333333 0.         0.        ]
 [0.         0.         0.         0.25       0.        ]
 [0.         0.         0.         0.         0.2       ]]
-------------------- A·A¯¹
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


> Otro concepto que se utiliza mucho en la ciencia de datos y machine learning es el concepto de matriz simétrica. Se dice que: *Una matriz es simétrica cuando su traspuesta es igual a la matriz original* es decir cuando A=A<sup>T</sup>