In [4]:
import numpy as np

In [5]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [6]:
A = matriz * vector
B = matriz.dot(vector)
print(A)
print(B)
print(vector)
print(matriz)

[[ 2  6]
 [ 6 12]
 [10 18]]
[ 8 18 28]
[2 3]
[[1 2]
 [3 4]
 [5 6]]
